const teamMembers = {
  core_committee: [
    {
      name: { firstName: "Daksh", lastName: "Bhatnagar" },
      avatarURL: "/images/team/daksh.jpeg",
      field: "OverAll Fest Coordinator",
      facebookLink: "",
      linkedinLink: "",
      twitterLink: "",
    },
    {
      name: { firstName: "Rakesh", lastName: "Raushan" },
      avatarURL: "/images/team/rakesh.jpeg",
      field: "Media and PR Coordinator",
      facebookLink: "",
      linkedinLink: "",
      twitterLink: "",
    },
    {
      name: { firstName: "Yash", lastName: "Rawal" },
      avatarURL: "/images/team/yash.png",
      field: "Sponsorship Head",
      facebookLink: "",
      linkedinLink: "",
      twitterLink: "",
    },
    {
      name: { firstName: "Kaushal", lastName: "Jangir" },
      avatarURL: "/images/team/kaushal.jpeg",
      field: "Event Head",
      facebookLink: "",
      linkedinLink: "",
      twitterLink: "",
    },
    {
      name: { firstName: "Gopi", lastName: "Krishnan" },
      avatarURL: "/images/team/gopi.jpeg",
      field: "Logistic Head",
      facebookLink: "",
      linkedinLink: "",
      twitterLink: "",
    },
    {
      name: { firstName: "Shivam", lastName: "Prakash" },
      avatarURL: "/images/team/shivam.png",
      field: "Creatives and Design Head",
      facebookLink: "",
      linkedinLink: "",
      twitterLink: "",
    },
    {
      name: { firstName: "Ajay", lastName: "" },
      avatarURL: "/images/team/ajay.png",
      field: "Event Head",
      facebookLink: "",
      linkedinLink: "",
      twitterLink: "",
    },
    {
      name: { firstName: "Aman ", lastName: "Kumar" },
      avatarURL: "/images/team/",
      field: "Technical Head",
      facebookLink: "",
      linkedinLink: "",
      twitterLink: "",
    },
  ],
};
export default teamMembers;
